### ISSUE TITLE
클러스터에 DBMS(Stateful Application) 실행

### ISSUE THREAD

**Issue by GangHun-Jo** [iamirongroot/WhatDoYouWant#3]
kubernetes docs
https://kubernetes.io/ko/docs/tasks/run-application/run-single-instance-stateful-application/

## 고민거리
- [ ] 현재 db 이중화가 되어 있지 않아서 위험 
-> ha(high availability) mysql을 클러스터 환경에서 어떻게 구현할 것인지 학습해보기
- [ ] kubernetes secret을 활용하여 접속 정보 관리
- [ ] DB ACL 필요성 및 관리 방안
- [ ] cronjob을 통해 dump할 필요성 고민
- [ ] 이외에도 클러스터 환경에서 db환경을 구축한 best practice 검색해보기
- [ ] pv, pvc에 대한 개념이 아직 확실치 않으니 학습해보기

## yaml 파일
- 서비스, 디플로이먼트
```
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
```
- pv, pvc
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

 `kubectl apply -f https://k8s.io/examples/application/mysql/mysql-pv.yaml`

` kubectl apply -f https://k8s.io/examples/application/mysql/mysql-deployment.yaml`

- mysql 클라이언트를 통해 db 접속
MySQL 클라이언트를 실행하는 파드를 클러스터에 생성하고, 서비스를 통하여 서버에 연결   
`kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysql -ppassword`
