### ISSUE TITLE
Ingress-nginx

### ISSUE THREAD

**Issue by GangHun-Jo** [iamirongroot/WhatDoYouWant#8]
https://kubernetes.github.io/ingress-nginx/deploy/

**Comment by GangHun-Jo** [comment]
> 위 가이드에 따라 ingress-nginx 네임스페이스에 ingress-controller를 생성하고
아래와 같이 ingress와 service 오브젝트를 생성한다.
ingress에는 뒷 단에서 어떤 서비스와 연결할지 명시

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wdyw-ingress-{{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: wdyw-svc-{{ .Release.Name }}
              servicePort: 3000
          - path: /api/v1
            pathType: Prefix
            backend:
              serviceName: wdyw-svc-{{ .Release.Name }}
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-{{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: intress-nginx-{{ .Release.Name }}
    app.kubernetes.io/part-of: intress-nginx-{{ .Release.Name }}
  ports:
    - targetPort: http
      port: 80
      name: http
    - targetPort: https
      port: 443
      name: https
  type: LoadBalancer
```

## 인그레스란
https://kubernetes.io/ko/docs/concepts/services-networking/ingress/
